## Stage 1 : build with maven builder image with native capabilities
FROM quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-25@sha256:1a47e85f8b945cd6819a9551d3e481609ea7fa5a0163d62f666f5e291491837f AS builder
COPY --chown=quarkus:quarkus --chmod=0755 mvnw /code/mvnw
COPY --chown=quarkus:quarkus .mvn /code/.mvn
COPY --chown=quarkus:quarkus pom.xml /code/
USER quarkus
WORKDIR /code
RUN ./mvnw -B quarkus:go-offline --no-transfer-progress
COPY src /code/src
RUN ./mvnw -B package -Dnative -DskipTests --no-transfer-progress --strict-checksums

# install additional packages
FROM registry.access.redhat.com/ubi9:9.8@sha256:8bf0e8f20737e9c8a68c8a498299e9504ab397b1b1f2837acb2fef12ec698f0e AS installer
RUN mkdir -p /mnt/rootfs
RUN dnf install --installroot /mnt/rootfs curl --releasever 9 --setopt install_weak_deps=false --nodocs -y \
    && dnf --installroot /mnt/rootfs clean all \
    && rpm --root /mnt/rootfs -e --nodeps setup

## Stage 2 : create the docker final image
FROM quay.io/quarkus/quarkus-micro-image:2.0@sha256:33d88f6b4f023dcea9a97df146a7ed22b7da4d03ef2fc134e5fae624f5578246
COPY --from=builder /code/target/*-runner /work/application
COPY --from=installer /mnt/rootfs /
WORKDIR /work/

# set up permissions for user `1001`
RUN chmod 775 /work /work/application \
  && chown -R 1001 /work \
  && chmod -R "g+rwX" /work \
  && chown -R 1001:root /work

LABEL org.opencontainers.image.url="https://cryptomator.org/hub/"
LABEL org.opencontainers.image.source="https://github.com/cryptomator/hub"
LABEL org.opencontainers.image.vendor="Skymatic GmbH"
EXPOSE 8080
USER 1001
ENV QUARKUS_HTTP_HOST=0.0.0.0
ENV QUARKUS_MICROMETER_EXPORT_PROMETHEUS_ENABLED=false

CMD ["./application"]