ALTER TABLE "vault" ALTER COLUMN "salt" DROP NOT NULL;
ALTER TABLE "vault" ALTER COLUMN "iterations" DROP NOT NULL;
ALTER TABLE "vault" ALTER COLUMN "masterkey" DROP NOT NULL;
ALTER TABLE "vault" ALTER COLUMN "auth_pubkey" DROP NOT NULL;
ALTER TABLE "vault" ALTER COLUMN "auth_prvkey" DROP NOT NULL;