CREATE TABLE "audit_event_setting_wot_update"
(
	"id"                BIGINT NOT NULL,
	"updated_by"        VARCHAR(255) COLLATE "C" NOT NULL,
	"wot_max_depth"     INTEGER NOT NULL,
	"wot_id_verify_len" INTEGER NOT NULL,
	CONSTRAINT "AUDIT_EVENT_SETTING_WOT_UPDATE_PK" PRIMARY KEY ("id"),
	CONSTRAINT "AUDIT_EVENT_SETTING_WOT_UPDATE_FK_AUDIT_EVENT" FOREIGN KEY ("id") REFERENCES "audit_event" ("id") ON DELETE CASCADE
);

CREATE TABLE "audit_event_user_keys_change"
(
	"id"           BIGINT NOT NULL,
	"changed_by"   VARCHAR(255) COLLATE "C" NOT NULL,
	"user_name"    VARCHAR NOT NULL,
	CONSTRAINT "AUDIT_EVENT_USER_ACCOUNT_SETUP_COMPLETE_PK" PRIMARY KEY ("id"),
	CONSTRAINT "AUDIT_EVENT_USER_ACCOUNT_SETUP_COMPLETE_FK_AUDIT_EVENT" FOREIGN KEY ("id") REFERENCES "audit_event" ("id") ON DELETE CASCADE
);

CREATE TABLE "audit_event_user_account_reset"
(
	"id"       BIGINT NOT NULL,
	"reset_by" VARCHAR(255) COLLATE "C" NOT NULL,
	CONSTRAINT "AUDIT_EVENT_USER_ACCOUNT_RESET_PK" PRIMARY KEY ("id"),
	CONSTRAINT "AUDIT_EVENT_USER_ACCOUNT_RESET_FK_AUDIT_EVENT" FOREIGN KEY ("id") REFERENCES "audit_event" ("id") ON DELETE CASCADE
);

CREATE TABLE "audit_event_user_setupcode_change"
(
	"id"         BIGINT NOT NULL,
	"changed_by" VARCHAR(255) COLLATE "C" NOT NULL,
	CONSTRAINT "AUDIT_EVENT_USER_SETUPCODE_CHANGE_PK" PRIMARY KEY ("id"),
	CONSTRAINT "AUDIT_EVENT_USER_ACCOUNT_SETUPCODE_CHANGE_EVENT" FOREIGN KEY ("id") REFERENCES "audit_event" ("id") ON DELETE CASCADE
);