apiVersion: v2
name: cryptomator-hub
home: https://cryptomator.org/hub/
icon: https://cryptomator.org/img/logo.png
description: Helm chart for deploying Cryptomator Hub with optional Keycloak and PostgreSQL
type: application
version: 0.1.3
appVersion: "1.5.0-alpha3"
kubeVersion: ">=1.27.0-0"
sources:
  - https://github.com/cryptomator/hub
keywords:
  - cryptomator
  - cryptomator hub
