global:
  host: hub.example.com

hub:
  database:
    password: replace-me
  admin:
    username: admin
    password: replace-me
    passwordTemporary: true
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
    limits:
      cpu: 1000m
      memory: 128Mi

keycloak:
  enabled: true
  database:
    password: replace-me
  admin:
    password: replace-me
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

postgres:
  enabled: true
  auth:
    adminPassword: replace-me
  storage:
    size: 20Gi
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 2000m
      memory: 1Gi
