global:
  host: ""

secrets:
  keepOnUninstall: true

hub:
  database:
    password: top-secret
  admin:
    username: admin
    password: admin
    passwordTemporary: true
  license:
    apiUrl: "https://api.staging.cryptomator.org/licenses"

keycloak:
  enabled: true
  database:
    password: top-secret
  admin:
    password: admin

postgres:
  enabled: true
  auth:
    adminPassword: top-secret
  storage:
    size: 1Gi
