package org.cryptomator.hub.api;

import jakarta.ws.rs.core.Response;

public enum ErrorCode {
	ADD_GROUP_MEMBER_FAILED(Response.Status.INTERNAL_SERVER_ERROR),
	CREATE_GROUP_FAILED(Response.Status.INTERNAL_SERVER_ERROR),
	CREATE_USER_FAILED(Response.Status.INTERNAL_SERVER_ERROR),
	DELETE_GROUP_FAILED(Response.Status.INTERNAL_SERVER_ERROR),
	DELETE_USER_FAILED(Response.Status.INTERNAL_SERVER_ERROR),
	DISABLE_USER_FAILED(Response.Status.INTERNAL_SERVER_ERROR),
	EMAIL_EXISTS(Response.Status.CONFLICT),
	ENABLE_USER_FAILED(Response.Status.INTERNAL_SERVER_ERROR),
	FEDERATED_IDENTITY_CHECK_FAILED(Response.Status.INTERNAL_SERVER_ERROR),
	GROUP_MEMBER_NOT_FOUND(Response.Status.NOT_FOUND),
	GROUP_NAME_EXISTS(Response.Status.CONFLICT),
	GROUP_NOT_FOUND(Response.Status.NOT_FOUND),
	READ_GROUP_MEMBERS_FAILED(Response.Status.INTERNAL_SERVER_ERROR),
	REMOVE_GROUP_MEMBER_FAILED(Response.Status.INTERNAL_SERVER_ERROR),
	UPDATE_GROUP_FAILED(Response.Status.INTERNAL_SERVER_ERROR),
	UPDATE_USER_FAILED(Response.Status.INTERNAL_SERVER_ERROR),
	UPDATE_USER_ROLES_FAILED(Response.Status.INTERNAL_SERVER_ERROR),
	USER_EXISTS(Response.Status.CONFLICT),
	USER_HAS_FEDERATED_IDENTITY(Response.Status.FORBIDDEN),
	USER_NOT_FOUND(Response.Status.NOT_FOUND),
	USERNAME_EXISTS(Response.Status.CONFLICT);

	private final Response.Status status;

	ErrorCode(Response.Status status) {
		this.status = status;
	}

	public Response.Status getStatus() {
		return status;
	}
}
