{{- if .Values.hub.metrics.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cryptomator-hub.fullname" . }}-secrets-hub-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cryptomator-hub.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.hub.metrics.username | quote }}
  password: {{ include "cryptomator-hub.resolvedHubMetricsPassword" . | quote }}
{{- end }}
