{{- if and .Values.hub.metrics.enabled .Values.hub.metrics.otlp.username .Values.hub.metrics.otlp.password }}
{{- $auth := printf "%s:%s" .Values.hub.metrics.otlp.username .Values.hub.metrics.otlp.password | b64enc }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cryptomator-hub.fullname" . }}-secrets-hub-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cryptomator-hub.labels" . | nindent 4 }}
  {{- if .Values.secrets.keepOnUninstall }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.hub.metrics.otlp.username | quote }}
  password: {{ .Values.hub.metrics.otlp.password | quote }}
  otlp_authorization: {{ printf "Authorization=Basic %s" $auth | quote }}
{{- end }}
