{{- if and .Values.hub.secrets.create (not .Values.hub.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cryptomator-hub.hubSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cryptomator-hub.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.hub.secrets.keys.systemClientSecret }}: {{ include "cryptomator-hub.resolvedSystemClientSecret" . | quote }}
  {{- if not .Values.postgres.enabled }}
  {{ .Values.hub.secrets.keys.dbPassword }}: {{ .Values.hub.secrets.data.dbPassword | quote }}
  {{- end }}
  {{ .Values.hub.secrets.keys.initialId }}: {{ .Values.hub.secrets.data.initialId | quote }}
  {{ .Values.hub.secrets.keys.initialLicense }}: {{ .Values.hub.secrets.data.initialLicense | quote }}
{{- end }}
