{{- if .Values.hub.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cryptomator-hub.fullname" . }}-secrets-hub
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cryptomator-hub.labels" . | nindent 4 }}
type: Opaque
stringData:
  hub_system_client_secret: {{ include "cryptomator-hub.resolvedSystemClientSecret" . | quote }}
  hub_db_password: {{ .Values.hub.database.password | quote }}
  hub_initial_id: {{ .Values.hub.secrets.initialId | quote }}
  hub_initial_license: {{ .Values.hub.secrets.initialLicense | quote }}
{{- end }}
