{{- if or .Values.keycloak.enabled .Values.keycloak.realmBootstrap.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cryptomator-hub.fullname" . }}-secrets-kc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cryptomator-hub.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.keycloak.enabled }}
  admin-username: {{ .Values.keycloak.admin.username | quote }}
  admin-password: {{ include "cryptomator-hub.resolvedKeycloakAdminPassword" . | quote }}
  db-password: {{ include "cryptomator-hub.resolvedKeycloakDbPassword" . | quote }}
  {{- end }}
  {{- if .Values.keycloak.realmBootstrap.enabled }}
  hub-admin-password: {{ include "cryptomator-hub.resolvedHubAdminPassword" . | quote }}
  realm.json: |
{{ include "cryptomator-hub.realmJson" . | indent 4 }}
  {{- end }}
{{- end }}
