apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cryptomator-hub.fullname" . }}-secrets-kc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cryptomator-hub.labels" . | nindent 4 }}
  {{- if .Values.secrets.keepOnUninstall }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
type: Opaque
stringData:
  {{- if .Values.keycloak.enabled }}
  kc_admin_password: {{ include "cryptomator-hub.resolvedKeycloakAdminPassword" . | quote }}
  kc_db_password: {{ include "cryptomator-hub.resolvedKeycloakDbPassword" . | quote }}
  {{- end }}
  realm.json: |
{{ include "cryptomator-hub.realmJson" . | indent 4 }}