{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cryptomator-hub.fullname" . }}-config-kc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cryptomator-hub.labels" . | nindent 4 }}
data:
  KC_DB: "postgres"
  KC_DB_URL: {{ if .Values.postgres.enabled }}{{ printf "jdbc:postgresql://%s:%v/%s" (print (include "cryptomator-hub.fullname" .) "-service-pg") .Values.postgres.service.port .Values.keycloak.database.name | quote }}{{ else }}{{ required "keycloak.database.url must be set when keycloak.enabled=true and postgres.enabled=false" .Values.keycloak.database.url | quote }}{{ end }}
  KC_DB_USERNAME: {{ .Values.keycloak.database.username | quote }}
  KC_HEALTH_ENABLED: "true"
  KC_METRICS_ENABLED: "true"
  KC_HTTP_ENABLED: "true"
  KC_PROXY_HEADERS: {{ .Values.keycloak.config.proxyHeaders | quote }}
  KC_HTTP_RELATIVE_PATH: {{ include "cryptomator-hub.keycloakRelativePath" . | quote }}
  KC_HOSTNAME: {{ include "cryptomator-hub.keycloakPublicUrl" . | quote }}
  KC_HOSTNAME_BACKCHANNEL_DYNAMIC: "true"
{{- end }}
