{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cryptomator-hub.fullname" . }}-secrets-pg
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cryptomator-hub.labels" . | nindent 4 }}
  {{- if .Values.secrets.keepOnUninstall }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
type: Opaque
stringData:
  pg_admin_password: {{ include "cryptomator-hub.resolvedPostgresAdminPassword" . | quote }}
  initdb.sql: |-
    {{- if .Values.keycloak.enabled }}
    CREATE USER {{ .Values.keycloak.database.username }} WITH ENCRYPTED PASSWORD '{{ include "cryptomator-hub.resolvedKeycloakDbPassword" . | replace "'" "''" }}';
    CREATE DATABASE {{ .Values.keycloak.database.name }} WITH ENCODING 'UTF8' OWNER {{ .Values.keycloak.database.username }};
    {{- end }}
    CREATE USER {{ .Values.hub.database.username }} WITH ENCRYPTED PASSWORD '{{ include "cryptomator-hub.resolvedHubDbPassword" . | replace "'" "''" }}';
    CREATE DATABASE {{ .Values.hub.database.name }} WITH ENCODING 'UTF8' OWNER {{ .Values.hub.database.username }};
{{- end }}
