{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cryptomator-hub.postgresSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cryptomator-hub.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-password: {{ .Values.postgres.auth.adminPassword | quote }}
  hub-password: {{ .Values.postgres.auth.hubPassword | quote }}
  keycloak-password: {{ .Values.postgres.auth.keycloakPassword | quote }}
  initdb.sql: |-
    CREATE USER {{ .Values.postgres.auth.keycloakUsername }} WITH ENCRYPTED PASSWORD '{{ .Values.postgres.auth.keycloakPassword }}';
    CREATE DATABASE {{ .Values.postgres.auth.keycloakDatabase }} WITH ENCODING 'UTF8' OWNER {{ .Values.postgres.auth.keycloakUsername }};
    CREATE USER {{ .Values.postgres.auth.hubUsername }} WITH ENCRYPTED PASSWORD '{{ .Values.postgres.auth.hubPassword }}';
    CREATE DATABASE {{ .Values.postgres.auth.hubDatabase }} WITH ENCODING 'UTF8' OWNER {{ .Values.postgres.auth.hubUsername }};
{{- end }}
