-- noinspection SqlNoDataSourceInspectionForFile

CREATE TABLE user
(
	id   VARCHAR(255) NOT NULL,
	name VARCHAR(255) NOT NULL,
	picture_url VARCHAR(255),
	email VARCHAR(255),
	CONSTRAINT PK_USER PRIMARY KEY (id)
);

CREATE TABLE grp
(
    id   VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT PK_GROUP PRIMARY KEY (id)
);

CREATE TABLE group_user
(
    group_id  VARCHAR(255) NOT NULL,
    user_id   VARCHAR(255) NOT NULL,
    CONSTRAINT PK_GROUP_USER PRIMARY KEY (user_id, group_id),
    CONSTRAINT FK_GROUP_USER_ON_GROUP FOREIGN KEY (group_id) REFERENCES grp (id) ON DELETE CASCADE,
    CONSTRAINT FK_GROUP_USER_ON_USER FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE
);

CREATE TABLE vault
(
	id         VARCHAR(255) NOT NULL,
	user_id    VARCHAR(255) NOT NULL,
	name       VARCHAR(255) NOT NULL,
	salt       VARCHAR(255) NOT NULL,
	iterations VARCHAR(255) NOT NULL,
	masterkey  VARCHAR(255) NOT NULL,
	CONSTRAINT PK_VAULT PRIMARY KEY (id),
	CONSTRAINT FK_VAULT_ON_USER FOREIGN KEY (user_id) REFERENCES user (id)
);

CREATE TABLE vault_user
(
	vault_id  VARCHAR(255) NOT NULL,
	user_id   VARCHAR(255) NOT NULL,
	CONSTRAINT PK_VAULT_USER PRIMARY KEY (vault_id, user_id),
	CONSTRAINT FK_VAULT_USER_ON_VAULT FOREIGN KEY (vault_id) REFERENCES vault (id) ON DELETE CASCADE,
	CONSTRAINT FK_VAULT_USER_ON_USER FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE
);

CREATE TABLE vault_group
(
    vault_id  VARCHAR(255) NOT NULL,
    group_id   VARCHAR(255) NOT NULL,
    CONSTRAINT PK_VAULT_GROUP PRIMARY KEY (vault_id, group_id),
    CONSTRAINT FK_VAULT_GROUP_ON_VAULT FOREIGN KEY (vault_id) REFERENCES vault (id) ON DELETE CASCADE,
    CONSTRAINT FK_VAULT_GROUP_ON_GROUP FOREIGN KEY (group_id) REFERENCES grp (id) ON DELETE CASCADE
);

CREATE TABLE device
(
	id        VARCHAR(255) NOT NULL,
	user_id   VARCHAR(255) NOT NULL,
	name      VARCHAR(255) NOT NULL,
	publickey VARCHAR(255) NOT NULL,
	CONSTRAINT PK_DEVICE PRIMARY KEY (id),
	CONSTRAINT FK_DEVICE_ON_USER FOREIGN KEY (user_id) REFERENCES user (id)
);

CREATE TABLE user_access
(
	device_id     VARCHAR(255) NOT NULL,
	user_id       VARCHAR(255) NOT NULL,
	vault_id      VARCHAR(255) NOT NULL,
	jwe           VARCHAR(2000) NOT NULL UNIQUE,
	CONSTRAINT PK_USER_ACCESS PRIMARY KEY (device_id, user_id, vault_id),
	CONSTRAINT FK_USER_ACCESS_ON_DEVICE FOREIGN KEY (device_id) REFERENCES device (id) ON DELETE CASCADE,
	CONSTRAINT FK_USER_ACCESS_ON_VAULT_USER FOREIGN KEY (vault_id, user_id) REFERENCES vault_user (vault_id, user_id) ON DELETE CASCADE
);

CREATE TABLE group_access
(
    device_id     VARCHAR(255) NOT NULL,
    group_id       VARCHAR(255) NOT NULL,
    vault_id      VARCHAR(255) NOT NULL,
    jwe           VARCHAR(2000) NOT NULL UNIQUE,
    CONSTRAINT PK_GROUP_ACCESS PRIMARY KEY (device_id, group_id, vault_id),
    CONSTRAINT FK_GROUP_ACCESS_ON_DEVICE FOREIGN KEY (device_id) REFERENCES device (id) ON DELETE CASCADE,
    CONSTRAINT FK_GROUP_ACCESS_ON_VAULT_GROUP FOREIGN KEY (vault_id, group_id) REFERENCES vault_group (vault_id, group_id) ON DELETE CASCADE
);