name: Build and test frontend on dependabot update
# for reasons, see https://github.com/cryptomator/hub/pull/459

on:
  pull_request:
    branches: [develop]
    paths:
      - 'frontend/package.json'
      - 'frontend/pnpm-lock.yaml'
      - 'frontend/pnpm-workspace.yaml'

permissions:
  contents: read

defaults:
  run:
    shell: bash

env:
  NODE_VERSION: 26
  JAVA_VERSION: 25

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.head_ref, 'dependabot/npm_and_yarn/') || startsWith(github.ref_name, 'dependabot/npm_and_yarn/') }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          package_json_file: frontend/package.json
      - name: Check lockfile integrity
        working-directory: frontend
        run: bash scripts/check-lockfile.sh
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          cache-dependency-path: frontend/pnpm-lock.yaml
        # no-frozen-lockfile option due to byte mismatch
      - name: Install frontend dependencies
        working-directory: frontend
        run: pnpm install --no-frozen-lockfile
      - name: Re-verify lockfile integrity after regeneration
        working-directory: frontend
        run: bash scripts/check-lockfile.sh
        # business as usual
      - name: Build and test frontend
        working-directory: frontend
        run: pnpm run test:coverage
      - name: Deploy frontend
        working-directory: frontend
        run: pnpm run dist
