name: Build Keycloak Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image Tag'
        required: true

env:
  NODE_VERSION: 26

defaults:
  run:
    shell: bash

jobs:
  build-image:
    name: Build Custom Keycloak Image
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for checkout
      id-token: write # Required for the attestations step
      attestations: write # Required for the attestations step
      artifact-metadata: write # Required for the attestations step
      packages: write # Required for pushing the image to GHCR
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          package_json_file: keycloak/themes/cryptomator/common/resources/package.json
      - name: Check lockfile integrity
        working-directory: keycloak/themes/cryptomator/common/resources
        run: bash scripts/check-lockfile.sh
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          cache-dependency-path: keycloak/themes/cryptomator/common/resources/pnpm-lock.yaml
      - name: Install Dependencies
        working-directory: keycloak/themes/cryptomator/common/resources
        run: pnpm install --frozen-lockfile
      - name: Build Theme
        working-directory: keycloak/themes/cryptomator/common/resources
        run: pnpm run build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0
      - name: Login to GHCR
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Container Image
        id: push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: keycloak
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/cryptomator/keycloak:${{ github.event.inputs.tag }}
      - name: Generate artifact attestation
        uses: actions/attest@1e69f48acb82d1966a394da916b4c1698aa569d6 # v4.2.2
        with:
          subject-name: ghcr.io/cryptomator/keycloak
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true