name: Build Keycloak Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image Tag'
        required: true

env:
  NODE_VERSION: 16

defaults:
  run:
    shell: bash

jobs:
  build-image:
    name: Build Custom Keycloak Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: keycloak/themes/cryptomator/common/resources/package-lock.json
      - name: Install Dependencies
        working-directory: keycloak/themes/cryptomator/common/resources
        run: npm install
      - name: Build Theme
        working-directory: keycloak/themes/cryptomator/common/resources
        run: npm run build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Container Image
        uses: docker/build-push-action@v6
        with:
          context: keycloak
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            ghcr.io/cryptomator/keycloak:${{ github.event.inputs.tag }}